<a href="https://colab.research.google.com/github/JoaoSchneiderr/Contagem-para-metas/blob/main/notebooks/Getting_started_with_google_colab_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importação de informações

In [46]:
!pip install gdown
!gdown --id 1GlMLuPx9CLWjJo9iOG0JHvz7ch_dTGee -O Dados.csv
import pandas as pd

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)
/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1GlMLuPx9CLWjJo9iOG0JHvz7ch_dTGee
To: /content/Dados.csv
100% 607k/607k [00:00<00:00, 9.44MB/s]

### 1. Quantidade total de acidentes em Nova Iguaçu

Você ja se perguntou quantos acidentes ocorrem em uma das cidades que é dito uma das piores cidades para se dirigir em 2025?

Neste Tópico irei mostrar a quantidade real de acidentes que ocorreram em 2025

In [57]:
acidentes_por_mes_adaptado = nova_iguacu_df.copy()
acidentes_por_mes_adaptado['data_inversa'] = pd.to_datetime(acidentes_por_mes_adaptado['data_inversa'])

meses_pt = {
    1: 'Janeiro', 2: 'Fevereiro', 3: 'Março', 4: 'Abril',
    5: 'Maio', 6: 'Junho', 7: 'Julho', 8: 'Agosto',
    9: 'Setembro', 10: 'Outubro', 11: 'Novembro', 12: 'Dezembro'
}

contagem_mes = acidentes_por_mes_adaptado['data_inversa'].dt.month.value_counts().sort_index()
contagem_mes.index.name = 'Divisão por mês'
display(contagem_mes.rename(index=meses_pt))

Divisão por mês
Janeiro       97
Fevereiro    153
Março        179
Abril        204
Maio         115
Junho        192
Julho        107
Agosto       164
Setembro     108
Outubro      128
Novembro     214
Dezembro     146
Name: count, dtype: int64

In [48]:
acidentes_total = len(nova_iguacu_df)
acidentes_total

1807

### 2. Gravidade dos acidentes por mês em Nova Iguaçu

Show! Agora que sabemos quantos acidentes por mês e quantos acidentes no total tiveram no ano de 2025, qual foi a gravidade deles?

In [61]:
nova_iguacu_df['data_inversa'] = pd.to_datetime(nova_iguacu_df['data_inversa'])
nova_iguacu_df['mes_num'] = nova_iguacu_df['data_inversa'].dt.month
meses_pt = {
    1: 'Janeiro', 2: 'Fevereiro', 3: 'Março', 4: 'Abril',
    5: 'Maio', 6: 'Junho', 7: 'Julho', 8: 'Agosto',
    9: 'Setembro', 10: 'Outubro', 11: 'Novembro', 12: 'Dezembro'
}
nova_iguacu_df['mes'] = nova_iguacu_df['mes_num'].map(meses_pt)

gravidade_mensal = nova_iguacu_df.groupby('mes')[['mortos', 'feridos_graves', 'feridos_leves', 'ilesos']].sum()

gravidade_mensal = gravidade_mensal.reindex([
    'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
    'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
], fill_value=0)

print("\nAnálise da Gravidade dos Acidentes por Mês em Nova Iguaçu:")
display(gravidade_mensal)

total_mortos_geral = gravidade_mensal['mortos'].sum()
total_feridos_graves_geral = gravidade_mensal['feridos_graves'].sum()
total_feridos_leves_geral = gravidade_mensal['feridos_leves'].sum()
total_ilesos_geral = gravidade_mensal['ilesos'].sum()

print("\n--- Totais Gerais (Ano de 2025) ---")
print(f"Total Geral de Mortos: {total_mortos_geral:.0f}")
print(f"Total Geral de Feridos Graves: {total_feridos_graves_geral:.0f}")
print(f"Total Geral de Feridos Leves: {total_feridos_leves_geral:.0f}")
print(f"Total Geral de Ilesos: {total_ilesos_geral:.0f}")

Análise da Gravidade dos Acidentes por Mês em Nova Iguaçu:

           mortos  feridos_graves  feridos_leves  ilesos
mes
Janeiro       4.0             7.0           33.0    46.0
Fevereiro     3.0            19.0           42.0    73.0
Março         1.0             5.0           84.0    75.0
Abril         8.0            10.0           67.0    76.0
Maio          0.0             8.0           42.0    52.0
Junho         9.0             8.0           70.0    65.0
Julho         1.0             9.0           36.0    52.0
Agosto        3.0             5.0           86.0    65.0
Setembro      5.0             3.0           51.0    42.0
Outubro       0.0             4.0           64.0    59.0
Novembro      5.0            11.0           92.0    91.0
Dezembro      0.0             4.0           76.0    57.0

--- Totais Gerais (Ano de 2025) ---
Total Geral de Mortos: 39
Total Geral de Feridos Graves: 93
Total Geral de Feridos Leves: 743
Total Geral de Ilesos: 753

Com isso podemos afirmar que 48.42% dos acidentes em Nova Iguaçu tiveram vítimas (mortos, feridos leves ou graves).

51.58% dos acidentes não registraram vítimas.

Isso representa que a taxa de acidentes com mortos é extremamente baixa, sendo de apenas 2.16% e a média de vitimas por acidente(incluindo mortos e feridos) de apenas 0.48

### 3. Tipos de acidentes

Nesta seção, vamos explorar os tipos de acidentes que ocorrem com maior frequência em Nova Iguaçu e identificar aqueles que resultam em maior número de vítimas

In [64]:
print("\n Tipos de Acidentes Mais Comuns")
tipos_acidentes_comuns = nova_iguacu_df['tipo_acidente'].value_counts().head(10)
display(tipos_acidentes_comuns)

gravidade_por_tipo_acidente = nova_iguacu_df.groupby('tipo_acidente')[['mortos', 'feridos_graves', 'feridos_leves']].sum()
gravidade_por_tipo_acidente['total_vitimas'] = gravidade_por_tipo_acidente['mortos'] + gravidade_por_tipo_acidente['feridos_graves'] + gravidade_por_tipo_acidente['feridos_leves']

tipos_acidentes_mais_graves = gravidade_por_tipo_acidente.sort_values(by='total_vitimas', ascending=False).head(10)

print("\n Tipos de Acidentes Mais Graves (Top 10 por Total de Vítimas)")
display(tipos_acidentes_mais_graves)

print("\n Classificação de Acidentes Mais Comuns")
classificacao_acidente_comum = nova_iguacu_df['classificacao_acidente'].value_counts()
display(classificacao_acidente_comum)

 Tipos de Acidentes Mais Comuns

tipo_acidente
Colisão traseira                 487
Queda de ocupante de veículo     351
Colisão lateral mesmo sentido    270
Tombamento                       166
Colisão transversal              113
Saída de leito carroçável         79
Colisão frontal                   64
Colisão com objeto                63
Atropelamento de Pedestre         62
Engavetamento                     61
Name: count, dtype: int64

 Tipos de Acidentes Mais Graves (Top 10 por Total de Vítimas)

,mortos,feridos_graves,feridos_leves,total_vitimas
tipo_acidente,,,,
Colisão traseira,7.0,15.0,191.0,213.0
Queda de ocupante de veículo,7.0,17.0,175.0,199.0
Colisão lateral mesmo sentido,1.0,16.0,103.0,120.0
Tombamento,4.0,8.0,87.0,99.0
Colisão transversal,0.0,11.0,40.0,51.0
Saída de leito carroçável,3.0,4.0,31.0,38.0
Colisão frontal,0.0,2.0,32.0,34.0
Colisão com objeto,6.0,5.0,21.0,32.0
Capotamento,0.0,4.0,25.0,29.0
Atropelamento de Pedestre,10.0,8.0,10.0,28.0

 Classificação de Acidentes Mais Comuns

classificacao_acidente
Com Vítimas Feridas    1543
Sem Vítimas             144
Com Vítimas Fatais      120
Name: count, dtype: int64

### 4. Veículos envolvidos

Vamos analisar os tipos de veículos mais frequentes nos acidentes em Nova Iguaçu, comparando categorias como carros, motos e caminhões, e verificando se há uma maior incidência de veículos mais antigos.

In [69]:
print("\n--- Top 10 Tipos de Veículos Mais Comuns nos Acidentes em Nova Iguaçu ---")
tipos_veiculo_comuns = nova_iguacu_df['tipo_veiculo'].value_counts().head(10)
display(tipos_veiculo_comuns)

--- Top 10 Tipos de Veículos Mais Comuns nos Acidentes em Nova Iguaçu ---

tipo_veiculo
Motocicleta        703
Automóvel          666
Caminhonete         93
Caminhão            69
Camioneta           60
Caminhão-trator     52
Semireboque         39
Desconhecido        37
Motoneta            23
Ônibus              21
Name: count, dtype: int64

São muitos veiculos! E entre os mais comuns?
Carros vs Motos vs Caminhões

Qual é aquele que mais se repete?

In [72]:
print("\n CARRO VS MOTO VS CAMINHÃO")
veiculo_especifico = nova_iguacu_df['tipo_veiculo'].value_counts().loc[['Automóvel', 'Motocicleta', 'Caminhão']]
display(veiculo_especifico)

 CARRO VS MOTO VS CAMINHÃO

tipo_veiculo
Automóvel      666
Motocicleta    703
Caminhão        69
Name: count, dtype: int64

### 5. Perfil das pessoas envolvidas

Certo, sabemos muito mais agora! Porém, como eram as pessoas que estavam envolvidas nesses acidentes?

In [77]:
df_perfil = nova_iguacu_df[['sexo', 'idade', 'estado_fisico', 'tipo_envolvido']].copy()
df_perfil['idade'] = pd.to_numeric(df_perfil['idade'], errors='coerce')
df_perfil = df_perfil.dropna(subset=['idade'])
display(df_perfil.head())

           sexo  idade estado_fisico tipo_envolvido
6539  Masculino   53.0         Ileso       Condutor
6540  Masculino   33.0         Óbito       Pedestre
6541  Masculino   53.0         Ileso       Condutor
6542  Masculino   33.0         Óbito       Pedestre
7521  Masculino   47.0         Ileso       Condutor

In [78]:
bins = [0, 18, 25, 35, 45, 55, 65, 100]
labels = ['0-17', '18-24', '25-34', '35-44', '45-54', '55-64', '65+']

df_perfil['faixa_etaria'] = pd.cut(df_perfil['idade'], bins=bins, labels=labels, right=False)

print("\nDistribuição por Faixa Etária (Indivíduos Envolvidos em Acidentes):")
display(df_perfil['faixa_etaria'].value_counts().sort_index())

Distribuição por Faixa Etária (Indivíduos Envolvidos em Acidentes):

faixa_etaria
0-17      25
18-24    162
25-34    472
35-44    420
45-54    293
55-64    148
65+       60
Name: count, dtype: int64

In [80]:
df_vitimas = df_perfil[df_perfil['estado_fisico'].isin(['Ferido Grave', 'Ferido Leve', 'Óbito'])]
idade_media_vitimas = df_vitimas['idade'].mean()

print(f"Idade média das vítimas (Ferido Grave, Ferido Leve ou Morto): {idade_media_vitimas:.2f} anos")

Idade média das vítimas (Ferido Grave, Ferido Leve ou Morto): 28.92 anos

In [83]:
print("\nDistribuição por Sexo (Indivíduos Envolvidos em Acidentes):")
contagem_sexo = df_perfil['sexo'].value_counts()
display(contagem_sexo)

porcentagem_sexo = df_perfil['sexo'].value_counts(normalize=True) * 100
print("\nPorcentagem por Sexo (Indivíduos Envolvidos em Acidentes):")
display(porcentagem_sexo)

Distribuição por Sexo (Indivíduos Envolvidos em Acidentes):

sexo
Masculino        1309
Feminino          312
Não Informado     179
Ignorado            7
Name: count, dtype: int64

Porcentagem por Sexo (Indivíduos Envolvidos em Acidentes):

sexo
Masculino        72.440509
Feminino         17.266187
Não Informado     9.905921
Ignorado          0.387382
Name: proportion, dtype: float64

In [85]:
print("\nContagem de Condutores vs. Passageiros:\n")
contagem_condutor_passageiro = df_perfil['tipo_envolvido'].value_counts().loc[['Condutor', 'Passageiro']]
display(contagem_condutor_passageiro)

Contagem de Condutores vs. Passageiros:

tipo_envolvido
Condutor      1361
Passageiro     363
Name: count, dtype: int64

### 6. Distribuição temporal
O que levou esses acidentes, o clima tem culpa no que ocorreu? Vamos analisar

In [86]:
print("\n Acidentes por Horário em Nova Iguaçu")
acidentes_por_horario = nova_iguacu_df['horario'].value_counts().sort_values(ascending=False)
display(acidentes_por_horario)

--- Acidentes por Horário em Nova Iguaçu ---

horario
17:00:00    53
02:50:00    51
08:00:00    41
11:45:00    37
20:30:00    36
            ..
22:05:00     1
22:32:00     1
15:50:00     1
15:23:00     1
02:45:00     1
Name: count, Length: 207, dtype: int64

In [87]:
print("\n--- Acidentes por Dia da Semana em Nova Iguaçu ---")
acidentes_por_dia_semana = nova_iguacu_df['dia_semana'].value_counts().sort_values(ascending=False)
display(acidentes_por_dia_semana)

--- Acidentes por Dia da Semana em Nova Iguaçu ---

dia_semana
domingo          387
segunda-feira    320
sexta-feira      272
terça-feira      245
sábado           232
quarta-feira     222
quinta-feira     129
Name: count, dtype: int64

In [88]:
print("\n Acidentes por Condição Meteorológica em Nova Iguaçu")
acidentes_por_condicao_metereologica = nova_iguacu_df['condicao_metereologica'].value_counts().sort_values(ascending=False)
display(acidentes_por_condicao_metereologica)

--- Acidentes por Condição Meteorológica em Nova Iguaçu ---

condicao_metereologica
Céu Claro         1233
Nublado            233
Chuva              132
Sol                112
Garoa/Chuvisco      75
Ignorado            22
Name: count, dtype: int64

In [89]:
print("\n Acidentes por Fase do Dia em Nova Iguaçu ")
acidentes_por_fase_dia = nova_iguacu_df['fase_dia'].value_counts()
display(acidentes_por_fase_dia)

--- Acidentes por Fase do Dia em Nova Iguaçu ---

fase_dia
Pleno dia      1111
Plena Noite     556
Amanhecer        87
Anoitecer        53
Name: count, dtype: int64

**Reasoning**:
The subtask is to analyze the severity of accidents by day/night phase. The next step is to implement the instructions by grouping the DataFrame by 'fase_dia' and summing the relevant severity columns.

In [90]:
print("\n Gravidade dos Acidentes por Fase do Dia em Nova Iguaçu ")
gravidade_por_fase_dia = nova_iguacu_df.groupby('fase_dia')[['mortos', 'feridos_graves', 'feridos_leves']].sum()
display(gravidade_por_fase_dia)

--- Gravidade dos Acidentes por Fase do Dia em Nova Iguaçu ---

             mortos  feridos_graves  feridos_leves
fase_dia
Amanhecer       5.0             4.0           31.0
Anoitecer       0.0             2.0           25.0
Plena Noite    25.0            32.0          224.0
Pleno dia       9.0            55.0          463.0